# Generated by Django 6.0.6 on 2026-06-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_user_aadhar_user_city_user_country_code_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('ceo', 'CEO'), ('md', 'MD'), ('hr', 'HR'), ('finance', 'Finance'), ('marketing', 'Marketing Team'), ('it', 'IT Team'), ('admin', 'Admin'), ('manager', 'Manager'), ('tl', 'TL')], default='employee', max_length=20),
        ),
    ]
