# Generated by Django 6.0.6 on 2026-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('personal_email', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], max_length=20)),
                ('marital_other', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('nationality', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=50)),
                ('current_state', models.CharField(max_length=50)),
                ('permanent_city', models.CharField(max_length=50)),
                ('permanent_state', models.CharField(max_length=50)),
                ('emergency_name', models.CharField(max_length=50)),
                ('emergency_relationship', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('passport', models.CharField(blank=True, max_length=20)),
                ('driving_license', models.CharField(blank=True, max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('percentage', models.CharField(max_length=10)),
                ('account_holder', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=100)),
                ('is_experienced', models.BooleanField(default=False)),
                ('prev_company', models.CharField(blank=True, max_length=100)),
                ('prev_designation', models.CharField(blank=True, max_length=100)),
                ('prev_experience', models.CharField(blank=True, max_length=10)),
                ('prev_last_working_day', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
