# Generated by Django 6.0.6 on 2026-06-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_employeeregistration_current_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('hr', 'HR'), ('marketing', 'Marketing'), ('digital_marketing', 'Digital Marketing'), ('webapp', 'WebApp'), ('mobile_app', 'Mobile App'), ('sales', 'Sales')], max_length=50)),
                ('designation', models.CharField(choices=[('associate', 'Associate'), ('intern', 'Intern'), ('tl', 'TL'), ('ceo', 'CEO'), ('md', 'MD')], max_length=50)),
                ('date_of_joining', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20)),
                ('reporting_tl', models.CharField(blank=True, max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('otc', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='hrms.employeeregistration')),
            ],
        ),
    ]
